# Generated by Django 5.2.8 on 2025-11-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'sku')},
        ),
    ]
